version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo y | android update sdk --no-ui --all --filter "android-30"
      - run: echo y | android update sdk --no-ui --all --filter "build-tools-30.0.3"
      - run: echo y | android update sdk --no-ui --all --filter "platform-tools"
      - run: npm install -g appium
      - run: npm install -g appium-doctor
      - run: appium-doctor --android
      - run: echo no | avdmanager create avd --force --name test --abi google_apis/x86_64 --package 'system-images;android-30;google_apis;x86_64'
      - run: emulator -avd test -no-window -no-audio &
      - run: android-wait-for-emulator
      - run: adb shell input keyevent 82 &
      - run: ./gradlew clean test

workflows:
  version: 2
  build:
    jobs:
      - build