version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      - BROWSERSTACK_USERNAME: orlandoavila_ve9kqN
      - BROWSERSTACK_ACCESS_KEY: LPbotyHHmZWvyWnkxnPH
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: ./gradlew assembleDebug

      # Run Appium tests
      - run:
          name: Run Appium tests
          command: |
            ./gradlew clean test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build