version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install -g appium
            npm install
      - run:
          name: Run single test
          command: |
            appium &
            ./gradlew clean test