version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            mkdir /tmp/appium_logs
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK 17
          command: |
            echo y | android update sdk --no-ui --all --filter "android-17"
            echo y | android update sdk --no-ui --all --filter "build-tools-28.0.3"
            echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
            echo y | android update sdk --no-ui --all --filter "extra-google-m2repository"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y build-essential
            sudo apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
