version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run:
          name: Install Android SDK
          command: |
            mkdir android-sdk
            cd android-sdk
            wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
            unzip -q commandlinetools-linux-7302050_latest.zip -d ~/android-sdk
            pwd
            ls
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

      - run:
          name: Install npm and Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            ./gradlew clean test