version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            mkdir /tmp/appium_logs
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK packages
          command: |
            mkdir -p "${ANDROID_HOME}"
            curl -L -o sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-7583922.zip
            unzip -d "${ANDROID_HOME}" sdk-tools.zip
            rm sdk-tools.zip
            echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools"
            echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;30.0.3"
            echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-30"
            echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;google;m2repository"
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
