version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
            sudo apt-get install -y openjdk-17-jdk
            mkdir -p ${ANDROID_HOME}
            cd ${ANDROID_HOME}
            curl -o sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip sdk.zip
            rm sdk.zip
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            echo 'export ANDROID_HOME=$HOME/android-sdk-linux' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> $BASH_ENV
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
