version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            npm install -g appium
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$PATH:$JAVA_HOME/bin
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O /tmp/tools.zip
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            unzip -q /tmp/tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
