version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run:
          name: Install Android SDK
          command: |
            mkdir android-sdk-linux
            cd android-sdk-linux
            curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
            unzip -q sdk.zip
            rm sdk.zip
            pwd
            ls

      - run:
          name: Install npm and Appium
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install -g appium
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            ./gradlew clean test