version: 2.1
jobs:
  build:
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
            sudo apt-get install -y wget
            