version: 2.1

orbs:
  android: circleci/android@2.0.0

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - android/install-npm
      - android/install-android-sdk:
          components: "platform-tools,build-tools;30.0.3,platforms;android-30"
      - run:
          name: Install dependencies
          command: |
            npm install -g appium
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            ./gradlew clean test