version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
            sudo apt-get install -y openjdk-17-jdk
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip -q sdk-tools-linux-4333796.zip -d $HOME/android-sdk
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
            $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-30"
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
