version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
      - image: ubuntu:latest
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            npm install appium
            echo 'export PATH="$PATH:./node_modules/.bin"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set up Java 17
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            curl -L -o corretto.deb https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.deb
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends ./corretto.deb
            sudo apt-get install -y -f
            rm corretto.deb
      - run:
          name: Set up JAVA_HOME and Android Emulator
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
            export PATH=$PATH:$JAVA_HOME/bin
            export ANDROID_EMULATOR_IP_ADDRESS=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}')
            export ANDROID_AVD_HOME=$HOME/.android/avd
            export ANDROID_SDK_ROOT=/usr/local/android-sdk-linux
            export ANDROID_HOME=/usr/local/android-sdk-linux
            yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86_64"
            echo "no" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 5X" --force
            ${ANDROID_HOME}/emulator/emulator -avd test -noaudio -no-window -gpu off -no-boot-anim -no-snapshot &
      - run:
          name: Install Android SDK
          command: |
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O /tmp/tools.zip
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            unzip -q /tmp/tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
      - run:
          name: Start Appium
          command: |
            appium --log-timestamp --port 4723 --default-capabilities '{"deviceName": "emulator-5554","platformName": "Android"}' &
            ps aux | grep appium
      - run:
          name: Install app dependencies
          command: |
            chmod +x gradlew
            sudo ./gradlew clean assembleDebug
      - run:
          name: Run tests
          command: |
            sudo ./gradlew clean test
