version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
      - image: ubuntu:latest
    environment:
      - BROWSERSTACK_USERNAME: orlandoavila_ve9kqN
      - BROWSERSTACK_ACCESS_KEY: LPbotyHHmZWvyWnkxnPH
    steps:
      - checkout
      - run:
          name: Set up Java 17
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$PATH:$JAVA_HOME/bin
            echo $JAVA_HOME
            java -version

      - run:
          name: Set up JAVA_HOME
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
            export PATH=$PATH:$JAVA_HOME/bin
      # Run Appium tests
      - run:
          name: Run Appium tests
          command: |
            chmod +x gradlew
            ./gradlew clean test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build