version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            mkdir /tmp/appium_logs
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK packages
          command: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java
            sdk install gradle
            sdk install android
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
