version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /usr/local/android-sdk-linux
      PATH: $PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            mkdir /tmp/appium_logs
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK packages
          command: |
            curl -L -o sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            mkdir -p $ANDROID_HOME
            unzip -d $ANDROID_HOME sdk-tools.zip
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
            $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "extras;google;m2repository" "extras;android;m2repository"
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
