version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up Java 17
          command: |
            curl -L -O https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
            tar xvf jdk-17_linux-x64_bin.tar.gz
            export JAVA_HOME=$PWD/jdk-17
            export PATH=$PATH:$JAVA_HOME/bin
            echo $JAVA_HOME
            java -version
      - run:
          name: Install Appium
          command: |
            sudo npm install -g appium --unsafe-perm=true
      - run:
          name: Install Android SDK
          command: |
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O /tmp/tools.zip
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            unzip -q /tmp/tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test