version: 2.1

orbs:
  android: circleci/android@1.1.3

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - android/setup-sdk:
          components: "platform-tools,build-tools;30.0.3,platforms;android-30"
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            ./gradlew clean test