version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /usr/local/android-sdk-linux
      PATH: $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Appium
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            mkdir /tmp/appium_logs
      - run:
          name: Install Node.js 18.x
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Android SDK
          command: |
            mkdir "$ANDROID_HOME" .android \
              && cd "$ANDROID_HOME" \
              && curl -o sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip \
              && unzip sdk.zip && rm sdk.zip \
              && yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "extras;android;m2repository" "extras;google;m2repository"
      - run:
          name: Run tests
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
