version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g appium
            sudo apt-get install -y openjdk-17-jdk
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            mkdir android-sdk-linux
            cd android-sdk-linux
            curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
            unzip -q sdk.zip
            rm sdk.zip
            echo 'export ANDROID_SDK_ROOT=$HOME/project/android-sdk-linux' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin' >> $BASH_ENV
            pwd
            ls
            cd platform-tools
            pwd
            ls -la $ANDROID_SDK_ROOT/platform-tools
      - run:
          name: Run single test
          command: |
            chmod +x gradlew
            appium &
            sudo ./gradlew clean test
